[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

[anonymous]
type=endpoint
transport=transport-udp
context=from-external
disallow=all
allow=ulaw
aors=anonymous

[anonymous]
type=aor
max_contacts=1
