[general]
persistentmembers = yes
autofill = yes

[support_queue]
strategy = ringall
timeout = 15
retry = 5
; Add members (human agents) to this queue
; member => PJSIP/agent1
; member => PJSIP/agent2
